;;; renerd-icons-dired-test.el --- Tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'dired)
(require 'subr-x)
(require 'renerd-icons-dired)

(defvar renerd-test--icon-calls 0)

(defun renerd-test--counted-icon (&rest _)
  (cl-incf renerd-test--icon-calls)
  "F")

(defmacro renerd-test--dired (files &rest body)
  "Create a Dired buffer with FILES and run BODY there."
  (declare (indent 1) (debug t))
  `(let ((directory (make-temp-file "renerd-dired-" t)))
     (unwind-protect
         (progn
           (dolist (file ,files)
             (if (string-suffix-p "/" file)
                 (make-directory (expand-file-name (string-remove-suffix "/" file) directory))
               (write-region "" nil (expand-file-name file directory) nil 'silent)))
           (save-window-excursion
             (let ((buffer (dired-noselect directory)))
               (unwind-protect
                   (with-current-buffer buffer
                     (switch-to-buffer buffer)
                     ,@body)
                 (when (buffer-live-p buffer) (kill-buffer buffer))))))
       (delete-directory directory t))))

(defun renerd-test--overlays ()
  (cl-remove-if-not (lambda (overlay)
                      (overlay-get overlay 'renerd-icons-dired-overlay))
                    (overlays-in (point-min) (point-max))))

(defun renerd-test--drain ()
  (let ((limit 1000))
    (while (and renerd-icons-dired--queue (> limit 0))
      (setq limit (1- limit))
      (renerd-icons-dired--process-queue (current-buffer)
                                         renerd-icons-dired--generation))
    (should-not renerd-icons-dired--queue)))

(ert-deftest renerd-icons-dired-visible-first-and-queue ()
  (renerd-test--dired (cl-loop for i below 500 collect (format "file-%04d.el" i))
    (let ((renerd-icons-dired-prefetch-lines 5)
          (renerd-icons-dired-chunk-size 20)
          (renerd-icons-dired-file-icon-function (lambda (&rest _) "F"))
          (renerd-icons-dired-dir-icon-function (lambda (&rest _) "D")))
      (goto-char (point-min))
      (forward-line 30)
      (let ((visible-end (point)))
        (goto-char (point-min))
        (cl-letf (((symbol-function 'window-end) (lambda (&rest _) visible-end)))
          (renerd-icons-dired-mode 1)))
      (let ((initial (length (renerd-test--overlays))))
        (should (> initial 0))
        (should (< initial 500))
        (should renerd-icons-dired--queue)
        (renerd-test--drain)
        ;; Only visible + prefetch region should have been queued, not all 500.
        (should (< (length (renerd-test--overlays)) 500))))))

(ert-deftest renerd-icons-dired-refresh-reuses-overlays ()
  (renerd-test--dired '("a.el" "b.el" "dir/")
    (let ((renerd-icons-dired-file-icon-function (lambda (&rest _) "F"))
          (renerd-icons-dired-dir-icon-function (lambda (&rest _) "D")))
      (renerd-icons-dired-mode 1)
      (renerd-test--drain)
      (let ((before (renerd-test--overlays)))
        (should before)
        (renerd-icons-dired-refresh)
        (renerd-test--drain)
        (should (equal before (renerd-test--overlays)))))))

(ert-deftest renerd-icons-dired-special-and-directory-prefixes ()
  (renerd-test--dired '("a.el" "dir/")
    (let ((renerd-icons-dired-file-icon-function (lambda (&rest _) "F"))
          (renerd-icons-dired-dir-icon-function (lambda (&rest _) "D"))
          (renerd-icons-dired-special-prefix-string "S\t")
          (renerd-icons-dired-infix-string "|"))
      (renerd-icons-dired-mode 1)
      (renerd-test--drain)
      (goto-char (point-min))
      (dired-goto-file default-directory)
      (let ((prefixes (mapcar (lambda (overlay)
                                (substring-no-properties
                                 (overlay-get overlay 'after-string)))
                              (renerd-test--overlays))))
        (should (member "S\t" prefixes))
        (should (member "F|" prefixes))
        (should (member "D|" prefixes))))))

(ert-deftest renerd-icons-dired-cache-and-clear ()
  (renerd-test--dired '("a.el" "b.el")
    (let ((renerd-test--icon-calls 0)
          (renerd-icons-dired-file-icon-function #'renerd-test--counted-icon)
          (renerd-icons-dired-dir-icon-function (lambda (&rest _) "D")))
      (clrhash renerd-icons-dired--file-cache)
      (renerd-icons-dired-mode 1)
      (renerd-test--drain)
      (let ((first renerd-test--icon-calls))
        (should (> first 0))
        (renerd-icons-dired-refresh t)
        (renerd-test--drain)
        (should (= renerd-test--icon-calls first))
        (renerd-icons-dired-clear-cache)
        (renerd-test--drain)
        (should (> renerd-test--icon-calls first))))))

(ert-deftest renerd-icons-dired-teardown-removes-resources ()
  (renerd-test--dired '("a.el" "b.el")
    (renerd-icons-dired-mode 1)
    (should (renerd-test--overlays))
    (should (memq #'renerd-icons-dired--post-command post-command-hook))
    (renerd-icons-dired-mode -1)
    (should-not (renerd-test--overlays))
    (should-not renerd-icons-dired--queue)
    (should-not (memq #'renerd-icons-dired--post-command post-command-hook))))

(ert-deftest renerd-icons-dired-no-whole-buffer-work-on-enable ()
  (renerd-test--dired (cl-loop for i below 10000 collect (format "file-%05d.el" i))
    (let ((renerd-icons-dired-prefetch-lines 20)
          (renerd-icons-dired-file-icon-function (lambda (&rest _) "F")))
      (goto-char (point-min))
      (forward-line 30)
      (let ((visible-end (point)))
        (goto-char (point-min))
        (cl-letf (((symbol-function 'window-end) (lambda (&rest _) visible-end)))
          (renerd-icons-dired-mode 1)))
      (let ((seen (+ (length (renerd-test--overlays))
                     (length renerd-icons-dired--queue))))
        ;; Batch window is 24-ish lines; with 20-line prefetch this must stay
        ;; far below the directory size.
        (should (< seen 200))))))

;;; renerd-icons-dired-test.el ends here
